### ISSUE TITLE
Błędy w wartościach

### ISSUE THREAD

**Issue by melwinek** [MichaluxPL/Sofar_LSW3#33]
Co jakiś czas do mqtt trafiają błędne wartości. Przynajmniej raz dziennie.
Szczegóły w załącznikach.
![Screenshot_20220323-194837_Home Assistant](https://user-images.githubusercontent.com/10649327/159774056-1aff61ec-4c3b-48dc-b1e9-4fc765e6f4ea.png)
![Screenshot_20220323-194816_Home Assistant](https://user-images.githubusercontent.com/10649327/159774064-8057ca53-4084-4bb1-a653-552fcefe7828.png)

**Comment by MichaluxPL** [comment]
To nie wina skryptu monitorującego. Niestety, ale takie wartości potrafi czasem zwracać logger/falownik. Chiński soft niestety, ale nie jest wolny od błędów :(

**Comment by melwinek** [comment]
A jakby skrypt, filtrował te nieprawidłowe wartości? Może uda się to zrobić? One dość znacznie różnią się od pozostałych.

**Comment by melwinek** [comment]
Na tą chwilę poradziłem sobie tak, zobaczymy czy zadziała.
```
sensor:
  - platform: mqtt
    name: "SofarInverter"
    state_topic: "SofarInverter"
    unit_of_measurement: "W"
    json_attributes_topic: "SofarInverter/attributes"

template:
  - sensor:
      - name: "sofar_status"
        state: "{{ state_attr('sensor.SofarInverter', 'Status')}}" 
   
  - sensor:
      - name: "sofar_u1"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Napięcie PV1 (V)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "V"

  - sensor:
      - name: "sofar_u2"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Napięcie PV2 (V)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "V"
        
  - sensor:
      - name: "sofar_i1"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Prąd PV1 (A)')}} {% else %} 'unknown' {% endif %}"  
        unit_of_measurement: "A"
        
  - sensor:
      - name: "sofar_i2"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Prąd PV2 (A)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "A"

  - sensor:
      - name: "sofar_p1"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Moc PV1 (W)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "W"
        
  - sensor:
      - name: "sofar_p2"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Moc PV2 (W)')}} {% else %} 'unknown' {% endif %}"  
        unit_of_measurement: "W"
        
  - sensor:
      - name: "sofar_pczynna"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Moc czynna (W)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "W"

  - sensor:
      - name: "sofar_pbierna"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Moc bierna (kVar)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "kVar"

  - sensor:
      - name: "sofar_czestotliwosc"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Częstotliwość sieci (Hz)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "Hz"

  - sensor:
      - name: "sofar_ul1"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Napięcie L1 (V)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "V"

  - sensor:
      - name: "sofar_il1"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Prąd L1 (A)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "A"

  - sensor:
      - name: "sofar_ul2"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Napięcie L2 (V)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "V"

  - sensor:
      - name: "sofar_il2"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Prąd L2 (A)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "A"

  - sensor:
      - name: "sofar_ul3"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Napięcie L3 (V)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "V"

  - sensor:
      - name: "sofar_il3"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Prąd L3 (A)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "A"

  - sensor:
      - name: "sofar_produkcja_calkowita"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Całkowita produkcja (kWh)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "kWh"

  - sensor:
      - name: "sofar_czas_pracy_calkowity"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Całkowity Czas pracy (h)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "h"
        
  - sensor:
      - name: "sofar_produkcja_dzienna"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Dzienna produkcja (Wh)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "Wh"

  - sensor:
      - name: "sofar_czas_pracy_dzienny"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Dzisiejszy czas pracy (min)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "min"

  - sensor:
      - name: "sofar_tmodulu"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Temperatura modułu (ºC)')}} {% else %} 'unknown' {% endif %}" 
        unit_of_measurement: "°C"

  - sensor:
      - name: "sofar_tfalownika"
        state: "{% if (state_attr('sensor.SofarInverter', 'Status') != 'BŁĄD') %} {{ state_attr('sensor.SofarInverter', 'Temperatura falownika (ºC)')}} {% else %} 'unknown' {% endif %}"  
        unit_of_measurement: "°C" 
```
